#!/usr/bin/env bash
# tests/chaos/generate-report.sh
#
# Generates automated resilience reports from chaos test results.
#
# Usage: ./generate-report.sh <results_directory>
#
# This script analyzes:
# - Recovery times for each experiment
# - Error patterns in operator logs
# - Resource convergence metrics
# - Overall system resilience score

set -euo pipefail

RESULTS_DIR="${1:-tests/chaos/results/$(ls -t tests/chaos/results | head -1)}"
REPORT_FILE="$RESULTS_DIR/resilience-report.md"

if [ ! -d "$RESULTS_DIR" ]; then
    echo "Error: Results directory $RESULTS_DIR not found"
    exit 1
fi

echo "Generating resilience report from $RESULTS_DIR..."

# Create report header
cat > "$REPORT_FILE" << 'EOF'
# Chaos Engineering Resilience Report

**Generated:** $(date)
**Results Directory:** $RESULTS_DIR
**Commit:** $(git rev-parse HEAD 2>/dev/null || echo "unknown")

## Executive Summary

This report analyzes the resilience of the Stellar-K8s operator under various failure scenarios.

## Experiment Results

EOF

# Analyze each experiment
for exp_log in "$RESULTS_DIR"/*-operator-logs.txt; do
    if [ ! -f "$exp_log" ]; then
        continue
    fi

    exp_name=$(basename "$exp_log" | sed 's/-operator-logs.txt//')
    exp_num=$(echo "$exp_name" | cut -d'-' -f1)

    echo "### Experiment $exp_num: $exp_name" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    # Count errors and warnings
    error_count=$(grep -c "ERROR\|error" "$exp_log" 2>/dev/null || echo 0)
    warn_count=$(grep -c "WARN\|warn" "$exp_log" 2>/dev/null || echo 0)
    panic_count=$(grep -c "panic\|PANIC" "$exp_log" 2>/dev/null || echo 0)

    # Check for recovery indicators
    recovery_lines=$(grep -c "Reconciling\|reconciled\|Applied" "$exp_log" 2>/dev/null || echo 0)

    # Calculate basic metrics
    total_lines=$(wc -l < "$exp_log" 2>/dev/null || echo 0)
    error_rate=$(( total_lines > 0 ? (error_count * 100) / total_lines : 0 ))

    echo "| Metric | Value |" >> "$REPORT_FILE"
    echo "|--------|-------|" >> "$REPORT_FILE"
    echo "| Total Log Lines | $total_lines |" >> "$REPORT_FILE"
    echo "| Error Count | $error_count |" >> "$REPORT_FILE"
    echo "| Warning Count | $warn_count |" >> "$REPORT_FILE"
    echo "| Panic Count | $panic_count |" >> "$REPORT_FILE"
    echo "| Recovery Operations | $recovery_lines |" >> "$REPORT_FILE"
    echo "| Error Rate | ${error_rate}% |" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    # Resilience assessment
    if [ "$panic_count" -eq 0 ] && [ "$recovery_lines" -gt 0 ]; then
        echo "**Resilience Score:** 🟢 PASS - No panics, recovery operations detected" >> "$REPORT_FILE"
    elif [ "$panic_count" -gt 0 ]; then
        echo "**Resilience Score:** 🔴 FAIL - Panics detected" >> "$REPORT_FILE"
    else
        echo "**Resilience Score:** 🟡 WARNING - Limited recovery activity" >> "$REPORT_FILE"
    fi

    echo "" >> "$REPORT_FILE"

    # Show key error patterns
    if [ "$error_count" -gt 0 ]; then
        echo "#### Top Error Patterns" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        grep "ERROR\|error" "$exp_log" | head -10 | sed 's/^/- /' >> "$REPORT_FILE" 2>/dev/null || true
        echo "" >> "$REPORT_FILE"
    fi
done

# Overall assessment
total_panics=$(find "$RESULTS_DIR" -name "*-operator-logs.txt" -exec grep -l "panic\|PANIC" {} \; 2>/dev/null | wc -l)
total_experiments=$(find "$RESULTS_DIR" -name "*-operator-logs.txt" | wc -l)

cat >> "$REPORT_FILE" << EOF

## Overall Assessment

**Total Experiments:** $total_experiments
**Experiments with Panics:** $total_panics

EOF

if [ "$total_panics" -eq 0 ]; then
    echo "**System Resilience:** 🟢 EXCELLENT - All experiments passed without panics" >> "$REPORT_FILE"
elif [ "$total_panics" -lt "$total_experiments" ]; then
    echo "**System Resilience:** 🟡 GOOD - Most experiments handled gracefully" >> "$REPORT_FILE"
else
    echo "**System Resilience:** 🔴 POOR - All experiments resulted in panics" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "## Recommendations" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if [ "$total_panics" -gt 0 ]; then
    echo "- Investigate panic causes and add proper error handling" >> "$REPORT_FILE"
    echo "- Consider implementing circuit breakers for external dependencies" >> "$REPORT_FILE"
    echo "- Add more comprehensive logging for debugging failure scenarios" >> "$REPORT_FILE"
fi

echo "- Monitor error rates in production and set up alerts" >> "$REPORT_FILE"
echo "- Regularly run chaos tests to catch regressions" >> "$REPORT_FILE"
echo "- Consider adding chaos testing to CI/CD pipeline for critical changes" >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Report generated by chaos testing suite*" >> "$REPORT_FILE"

echo "Report generated: $REPORT_FILE"